### ISSUE TITLE
When add a new JSON based curl task, it failed with error "Save failed, see errors below"

### ISSUE THREAD

**Issue by binjiang858** [gocd/sample-plugins#4]
The "Save failed, see errors below" is on JSON based curl task for both 14.4 and 15.1.  

Adding curl-plugin-old-api-based task is fine.

**Comment by jmnarloch** [comment]
Yes I have the same issue, I am running Go on OS X in version 15.1.0 with stack trace in logs:

```
2015-09-23 19:57:02,192 ERROR [540585569@qtp-117244645-17] GoConfigDataSource:214 - Configuration file is not valid : This field is required
com.thoughtworks.go.config.exceptions.GoConfigInvalidException: This field is required
    at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:142)
    at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:115)
    at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:86)
    at com.thoughtworks.go.config.GoConfigDataSource.configAsXml(GoConfigDataSource.java:313)
    at com.thoughtworks.go.config.GoConfigDataSource.getModifiedConfig(GoConfigDataSource.java:244)
    at com.thoughtworks.go.config.GoConfigDataSource.writeWithLock(GoConfigDataSource.java:201)
    at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:97)
    at com.thoughtworks.go.config.GoConfigFileDao.updateConfig(GoConfigFileDao.java:222)
    at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:260)
    at com.thoughtworks.go.server.service.GoConfigService.updateConfigFromUI(GoConfigService.java:305)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

The worst thing is that I had already templated my plugin based on the curl task sample and it is facing exactly same error.

@mdaliejaz, @arikagoyal cc @srinivasupadhya do you by any chance might know what is wrong here?

**Comment by zabil** [comment]
Looks like the additional options field is mandatory.
As a temporary fix you can pass a flag like -v and save the task.

<img width="306" alt="screen shot 2015-09-24 at 12 11 42 pm" src="https://cloud.githubusercontent.com/assets/54427/10066943/601e1cb6-62b5-11e5-82b6-7ee2574defe1.png">

**Comment by zabil** [comment]
Also this repository is outdated.

For now pick up the right version of the sample from here (which works without the issue mentioned above)

https://github.com/gocd/gocd/tree/c3c6196fa9427a85faac097b8ca9667174d40066/plugin-infra/sample-plugins/curl-plugin

We wil be updating this soon.

**Comment by jmnarloch** [comment]
Thanks @zabil, with your comment I was able to tackle down what was the problem. It turn out that in my configuration response I wasn't specifing the `required` field value which later ended with exactly same validation issue. Apparently each configuration property is required by default, unless specified explicitly.

This what also happens in curl example, probably the configuration should have additional entry for `required` false for the additional options.

Either way thanks again, you save me a lot of time looking for the solution.
